# Change these first
owner: travelallfly # Your GitHub organization or username, where this repository lives
repo: platform-upptime-qa # The name of this repository

sites:
  - name: Quest
    url: https://quest.qa.allfly.io
  - name: API (CORE)
    url: https://api.quest.qa.allfly.io/info

assignees:
  - hsteidel
  - NCLlamas


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.quest.qa.allfly.io
  # baseUrl: /your-repo-name
  logoUrl: https://cdn.prod.website-files.com/635694594a52ff25573355d8/63569d6112cf969ab22c8e6b_logo.svg
  name: Quest QA Status
  introTitle: "QA System Status"
  introMessage: Welcome to the QA System Status page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
